# Randomised trials

Our main focus in these notes will be on randomised trials done in the lab or field (e.g. schools, firms, health centres, community) to establish the causal impact of an intervention. The causal impact is the difference in outcomes caused by the intervention. It is the comparison of what happened with the program with what happened without the intervention.

The fundamental problem of causal inference: we can never observe the same people at the same time both with and without the intervention. We never observe the counterfactual. So we have to mimic the counterfactual.

**What is the best way to mimic the counterfactual?**

```{r echo=FALSE}

opts_counterfactual <-c(
  "Compare the outcome of people who took up the program with the outcome of people who did not take up the program",
  "Compare the outcome of people before they take up the program with the outcome of people after they take up the program",
  answer = "Compare the outcome of people randomly assigned into the program with the outcome of people randomly out of the program"
)

```

`r longmcq(opts_counterfactual)`

`r hide("Click here to see an explanation")`

What is the main issue in comparing people who take up the program with people who do not take up the program?

Selection matters: those who signed up or are chosen for a program are different from those who do not. They will vary in terms of what we can observe (e.g. education, income) and in terms of what we cannot observe (e.g. motivation, effort).

If we compare outcomes for those with and without the program, the difference will have two parts:

That are caused by the program
That are caused by underlying differences between participants and non-participants
Our estimate of impact will not, on average, be equal to the true impact of the program unless (2) is zero and there is no selection bias.

Comparing the outcome of people before and after the program risks the presence of other changes during that time. For example, did the program increase their spending, or did their spending increase as it is approaching Christmas?

`r unhide()`